# Generated by Django 3.0.5 on 2020-04-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('age', models.IntegerField()),
                ('activity', models.CharField(choices=[('Sedentary (little or no exercise)', 'Sedentary (little or no exercise)'), ('Lightly active (1-3 days/week)', 'Lightly active (1-3 days/week)'), ('Moderately active (3-5 days/week)', 'Moderately active (3-5 days/week)'), ('Very active (6-7 days/week)', 'Very active (6-7 days/week)'), ('Super active (twice/day)', 'Super active (twice/day)')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Details',
            },
        ),
    ]
